publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAI5tZC/Vs6O2gVbdy56o4QAUf5/Xfp59AQXaq4ZOwZBFGA0HjXzxhU/+QcWQ/VQFOesHeBMav7kjVQGubzJT0NECAwEAAQ==
#datasource
spring:
  #datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.101.184.178/garbage?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: xdx
    password: LWraPb9+9RNbgseugaN8fpiIDCvCc73MpjS5Frf3sz5CE2KLkK8DwwCj+1d9LWRW3KnKLcl41RyAAVWCDrF3Yg==

    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      filters: config,stat,slf4j,custom
      filter:
        config:
          enabled: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=${public-key}
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true

xdx: test