public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAOpnrM+yYs8H2O0fmT1A+6oE82hHApMoP7kMbFuB0O0pSISTXQOse+SuXM8RP/9Q42d+EXc1mct82IMrLNq3yM0CAwEAAQ==
#datasource
spring:
  #datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/garbage?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 408juanrB5JDul+j38z9EpuIUFAr4kz6qjGJS7HED4r7oAASjRGAhhjH0qaK4ezriXZoZWrKTSaEaZI/7HqeWA==

    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      filters: config,stat,slf4j,custom
      filter:
        config:
          enabled: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=${public-key}
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
xdx: dev
# 线程池参数配置
async:
  executor:
    thread:
      core_pool_size: 6
      max_pool_size: 6
      queue_capacity: 9999
      name:
        prefix: async-service-
